apiVersion: v1
kind: Service
metadata:
  name: eksdemo-frontend
  annotations:
    # Cloud Map Service name
    external-dns.alpha.kubernetes.io/hostname: eksdemo-frontend.awsrocks.net.
    # ARN of ACM certificate for ELB
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 	arn:aws:acm:us-west-2:ACCOUNTNUMBER:certificate/CERTARN
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    # Backend talks over HTTP
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http    
spec:
  selector:
    app: eksdemo-frontend
  type: LoadBalancer
  ports:
   -  protocol: TCP
      name: http
      port: 80
      targetPort: 3000
   -  protocol: TCP
      name: https
      port: 443
      targetPort: 3000      

